[build]
  publish = "dist"
  command = "npm run build"

# Si un JSON bajo /data no existe, devolver 404 real (no index.html)
[[redirects]]
  from = "/data/*"
  to = "/404.html"
  status = 404

# Fallback SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
